SistemaGerenciamento/Controllers/ItemDoMenus1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaGerenciamento.Models;

namespace SistemaGerenciamento.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ItemDoMenus1Controller : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ItemDoMenus1
        public ActionResult Index()
        {
            var itensDoMenu = db.ItensDoMenu.Include(i => i.Categoria);
            return View(itensDoMenu.ToList());
        }

        // GET: ItemDoMenus1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Inclui o relacionamento com Categoria ao buscar o item
            var itemDoMenu = db.ItensDoMenu.Include(i => i.Categoria).FirstOrDefault(i => i.Id == id);
            if (itemDoMenu == null)
            {
                return HttpNotFound();
            }

            return View(itemDoMenu);
        }

        // GET: ItemDoMenus1/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(db.CategoriaDoMenus, "Id", "Nome");
            return View();
        }

        // POST: ItemDoMenus1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Preco,Disponivel,CategoriaId,ImageFile")] ItemDoMenu itemDoMenu)
        {
            if (ModelState.IsValid)
            {
                if (itemDoMenu.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(itemDoMenu.ImageFile.FileName);
                    string extension = Path.GetExtension(itemDoMenu.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    itemDoMenu.Image = "/image/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/image/"), fileName);

                    // Salva a imagem no diretório
                    itemDoMenu.ImageFile.SaveAs(fileName);
                }

                db.ItensDoMenu.Add(itemDoMenu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(db.CategoriaDoMenus, "Id", "Nome", itemDoMenu.CategoriaId);
            return View(itemDoMenu);
        }

        // GET: ItemDoMenus1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemDoMenu itemDoMenu = db.ItensDoMenu.Find(id);
            if (itemDoMenu == null)
            {
                return HttpNotFound();
            }

            // Preenche PrecoString com o valor atual de Preco
            itemDoMenu.PrecoString = itemDoMenu.Preco.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture);

            // Passa a lista de categorias como SelectList para a view
            ViewBag.CategoriaId = new SelectList(db.CategoriaDoMenus, "Id", "Nome", itemDoMenu.CategoriaId);

            return View(itemDoMenu);
        }

        // POST: ItemDoMenus1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,PrecoString,Disponivel,CategoriaId,Image,ImageFile")] ItemDoMenu itemDoMenu)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Verifica se `PrecoString` não é nulo ou vazio antes de converter
                    if (!string.IsNullOrEmpty(itemDoMenu.PrecoString))
                    {
                        itemDoMenu.Preco = decimal.Parse(itemDoMenu.PrecoString, System.Globalization.CultureInfo.InvariantCulture);
                    }
                    else
                    {
                        // Define um valor padrão ou gera um erro de validação se o campo estiver vazio
                        ModelState.AddModelError("PrecoString", "O campo Preço é obrigatório.");
                        ViewBag.CategoriaId = new SelectList(db.CategoriaDoMenus, "Id", "Nome", itemDoMenu.CategoriaId);
                        return View(itemDoMenu);
                    }
                }
                catch (FormatException)
                {
                    ModelState.AddModelError("PrecoString", "Formato inválido. Use ponto como separador decimal.");
                    ViewBag.CategoriaId = new SelectList(db.CategoriaDoMenus, "Id", "Nome", itemDoMenu.CategoriaId);
                    return View(itemDoMenu);
                }

                // Processamento da imagem, se aplicável
                if (itemDoMenu.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(itemDoMenu.ImageFile.FileName);
                    string extension = Path.GetExtension(itemDoMenu.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    itemDoMenu.Image = "/image/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/image/"), fileName);
                    itemDoMenu.ImageFile.SaveAs(fileName);
                }

                db.Entry(itemDoMenu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Passa a lista de categorias novamente se houver erro na submissão do formulário
            ViewBag.CategoriaId = new SelectList(db.CategoriaDoMenus, "Id", "Nome", itemDoMenu.CategoriaId);
            return View(itemDoMenu);
        }

        // GET: ItemDoMenus1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemDoMenu itemDoMenu = db.ItensDoMenu.Find(id);
            if (itemDoMenu == null)
            {
                return HttpNotFound();
            }
            return View(itemDoMenu);
        }

        // POST: ItemDoMenus1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemDoMenu itemDoMenu = db.ItensDoMenu.Find(id);
            db.ItensDoMenu.Remove(itemDoMenu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaGerenciamento/Views/ItemDoMenus1/Create.cshtml
@model SistemaGerenciamento.Models.ItemDoMenu

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "ItemDoMenus1", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ItemDoMenu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disponivel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Disponivel)
                    @Html.ValidationMessageFor(model => model.Disponivel, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, "CategoriaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" onchange="previewImage(event)" />
                <br />
                <img id="preview" src="#" alt="Image preview" style="display:none; width:150px; height:150px;" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index")
            </div>
            
        </div>
    </div>
}

<script>function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.getElementById('preview');
            output.src = reader.result;
            output.style.display = 'block';
        }
        reader.readAsDataURL(event.target.files[0]);
    }</script>

SistemaGerenciamento/Views/ItemDoMenus1/Delete.cshtml
@model SistemaGerenciamento.Models.ItemDoMenu

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ItemDoMenu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disponivel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Disponivel)
        </dd>

        <dt>
            Imagem
        </dt>
        <dd>
            @if (!string.IsNullOrEmpty(Model.Image))
            {
                <img src="@Model.Image" width="100px" height="60px" alt="Imagem" />
            }
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SistemaGerenciamento/Views/ItemDoMenus1/Details.cshtml
@model SistemaGerenciamento.Models.ItemDoMenu

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ItemDoMenu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Categoria</dt>
        <dd>
            @if (Model.Categoria != null)
            {
                @Model.Categoria.Nome
            }
            else
            {
                <span>Não especificada</span>
            }
        </dd>

        <dt>Nome</dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>Preço</dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>Disponível</dt>
        <dd>
            @Html.DisplayFor(model => model.Disponivel)
        </dd>

        <dt>Imagem</dt>
        <dd>
            @if (!string.IsNullOrEmpty(Model.Image))
            {
                <img src="@Model.Image" width="100px" height="60px" alt="Imagem" />
            }
            else
            {
                <span>Imagem não disponível</span>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SistemaGerenciamento/Views/ItemDoMenus1/Edit.cshtml
@model SistemaGerenciamento.Models.ItemDoMenu

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ItemDoMenus1", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ItemDoMenu</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Image) <!-- Armazena o caminho atual da imagem -->

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrecoString, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PrecoString, new { @class = "form-control", @id = "PrecoString", @type = "text" })
            @Html.ValidationMessageFor(model => model.PrecoString, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Disponivel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Disponivel)
                @Html.ValidationMessageFor(model => model.Disponivel, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
        </div>
    </div>


    <!-- Campo de upload de imagem -->
    <div class="form-group">
        @Html.Label("Imagem Atual", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img id="currentImage" src="@Model.Image" width="100px" height="60px" alt="Imagem Atual" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, "Atualizar Imagem", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" id="ImageFile" accept="image/*" />
            @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        // Substitui vírgula por ponto no campo PrecoString
        document.getElementById("PrecoString").addEventListener("input", function () {
            this.value = this.value.replace(",", ".");
        });

        // Pré-visualização da nova imagem
        document.getElementById("ImageFile").addEventListener("change", function (event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    document.getElementById("currentImage").src = e.target.result;
                };
                reader.readAsDataURL(file);
            }
        });
    </script>
}

SistemaGerenciamento/Views/ItemDoMenus1/Index.cshtml
@model IEnumerable<SistemaGerenciamento.Models.ItemDoMenu>

@{
    ViewBag.Title = "Itens";
}

<h2>Itens</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Disponivel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponivel)
            </td>
            <td>
                <img src="@item.Image" width="80px" height="50px" alt="Image preview" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>